### ISSUE TITLE
PlaystoreApp not same as the Code

### ISSUE THREAD

**Issue by tioannidis** [varunon9/pocket-ai#1]
Hi,
first, thanks for the Code sharing, but you should mention that your Playstore [App ](https://play.google.com/store/apps/details?id=me.varunon9.pocket_ai)Version is not the same as the code here!

As it looks below, your application sends the Querries to you, but i can't find this part in your query code. so it would be fair to communicate this openly.
![Screenshot_20230318-193424](https://user-images.githubusercontent.com/1592909/226129524-f0540c4a-a1e9-4d10-a5ef-d3f22ddca7aa.png)

my2cents

**Comment by varunon9** [comment]
Hi @tioannidis

This codebase is in sync with Playstore. All the queries to bot are sent to Firestore for analytics. 
Adding the relevant code and file name here for reference-

```
  void saveUserMessageToFirestore(String userMessage) {
    // store user queries to Firestore for study & analytics
    String? deviceId = Globals.deviceId;
    if (deviceId != null) {
      db
          .collection(FirestoreCollectionsConst.userMessagesToBot)
          .doc(deviceId)
          .collection(FirestoreCollectionsConst.messages)
          .doc()
          .set({'message': userMessage, 'time': FieldValue.serverTimestamp()});
    }
  }
```

https://github.com/varunon9/pocket-ai/blob/master/lib/src/modules/chat/screens/chat_screen.dart

**Comment by tioannidis** [comment]
@varunon9  thanks for the clarification!
