### ISSUE TITLE
Please add support to render the API markdown response beautifully 

### ISSUE THREAD

**Issue by arverma** [varunon9/pocket-ai#3]
Currently the code is not displayed properly. It is being displayed in markdown. 

Requirement: Render the markdown beautifully in the output. Ca
![Screenshot_20230407-230411](https://user-images.githubusercontent.com/24602870/230652242-6dacf95c-7063-485c-b4aa-b4d2606c24ce.png)

**Comment by varunon9** [comment]
![Screenshot_1680945074](https://user-images.githubusercontent.com/9805036/230713620-6abbf254-e579-4271-9ee3-e79dc9982bb3.png)

Thanks for raising this, It'll be available in v1.1.2 on Playstore

**Comment by arverma** [comment]
@varunon9 Thanks for quick fix
